apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-svc"
  labels:
    app: "{{ .Chart.Name }}-svc"
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: {{ .Chart.Name }}
